name: Go
on: [push]
jobs:

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -o ./gels-windows.exe -v .

    - uses: actions/upload-artifact@master
      with:
        name: gels-windows.exe
        path: ./gels-windows.exe

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -o ./gels -v .

    - uses: actions/upload-artifact@master
      with:
        name: gels-linux
        path: ./gels

  build-macos:
    name: Build on Mac OS X
    runs-on: macOS-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -o ./gels -v .

    - uses: actions/upload-artifact@master
      with:
        name: gels-macosx
        path: ./gels
